#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_PX4_NAVIGATOR)  += px4navigator

px4navigator: libmuslc libsel4 librefossys librefos libdatastruct libuclibc++ libpx4drivers libpx4compat libpx4geo libpx4geo_lookup libpx4controllib libpx4dataman libpx4fw_pos_control_l1 libpx4uorb libpx4systemlib libpx4mathlib
