#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_PX4_MAVLINK)  += px4mavlink

px4mavlink: libmuslc libsel4 librefossys librefos libdatastruct libuclibc++ libpx4drivers libpx4compat libpx4controllib libpx4systemlib libpx4uorb libpx4conversion libpx4unit_test libpx4dataman
