#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

libs-$(CONFIG_LIB_PX4_FW_POS_CONTROL_L1) += libpx4fw_pos_control_l1

libpx4fw_pos_control_l1: common libuclibc++
